
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-dev
WORKDIR /app

COPY ["StoreManagement.Application/*.csproj", "./StoreManagement.Application/"]
COPY ["StoreManagement.Domain/*.csproj", "./StoreManagement.Domain/"]
COPY ["StoreManagement.Infrastructure/*.csproj", "./StoreManagement.Infrastructure/"]
COPY ["StoreManagement/*.csproj", "./StoreManagement/"]

# Restore dependencies
RUN dotnet restore "StoreManagement.Application/*.csproj"
RUN dotnet restore "StoreManagement.Domain/*.csproj"
RUN dotnet restore "StoreManagement.Infrastructure/*.csproj"
RUN dotnet restore "StoreManagement/*.csproj"

COPY . ./

RUN dotnet publish -c release -o out

FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
EXPOSE 80
COPY --from=build-dev /app/out .
ENTRYPOINT [ "dotnet", "StoreManagement.dll" ]

