version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: src/Presentation/Dockerfile
    ports:
      - "5263:5263" # Expose the API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=EasyStoreManagement;User=thien2;Password=123456;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest-ubuntu
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "123456"
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

volumes:
  dbdata:
